import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavPar from "./component/NavPar";
import Foter from "./component/Foter";
import ReduxProvider from "./reduxProvider";
import BodyWrapper from "./BodyWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "online-store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body>
        <ReduxProvider>
          <BodyWrapper>
            <div
              className={`${geistSans.variable} ${geistMono.variable}`}
              style={{
                display: "flex",
                flexDirection: "column",
                margin: "0",
                minHeight: "100vh",
              }}
            >
              <NavPar />
              <main style={{ flex: 1 }}>{children}</main>
              <Foter />
            </div>
          </BodyWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
