import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavPar from "./component/NavPar";
import Foter from "./component/Foter";
import ReduxProvider from "./reduxProvider";
import BodyWrapper from "./BodyWrapper";
import AlertTagelPrudact from "./component/AlertTagelPrudact";
import { Roboto } from "next/font/google";
const roboto = Roboto({
  subsets:['latin'],
  weight:'400'
})


export const metadata = {
  title: "online-store",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body>
        <ReduxProvider>
          <BodyWrapper>
            <div
              className={roboto.className}
              style={{
                display: "flex",
                flexDirection: "column",
                margin: "0",
                minHeight: "100vh",
              }}
            >
              <NavPar />
              <main style={{ flex: 1 }}>{children}</main>
              <Foter />
              <AlertTagelPrudact/>
            </div>
          </BodyWrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}
